--찜목록에 추가기능 (아이디=? 11부분=?) (23:test한 아이디번호)
INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),11,0)

INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
23,11,0)

--찜목록 삭제기능 (아이디=? 11부분=?)
DELETE FROM BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND ITEMID=11 AND COUNT=0

DELETE FROM BASKET WHERE MEMID=
23 AND ITEMID=11 AND COUNT=0

--찜목록 보기 기능(아이디=?)
SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0

SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
23 AND COUNT=0

--찜,장바구니 3개씩 보기기능
SELECT * FROM(
SELECT ROWNUM RNUM, AA.* FROM
(SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0 ORDER BY BASID DESC) AA
) WHERE RNUM>=1 AND RNUM<=3

SELECT * FROM(
SELECT ROWNUM RNUM, AA.* FROM
(SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
23 AND COUNT=0 ORDER BY BASID DESC) AA
) WHERE RNUM>=1 AND RNUM<=3

--총 찜한 개수 구하기(페이지 넘버 찾기 위함)
SELECT NVL(COUNT(BASID),0) CNT FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0 ORDER BY BASID DESC


--테스트용 데이터 집어넣기
SELECT * FROM MEMBERINFO;
SELECT * FROM BASKET;
SELECT * FROM ITEMINFO;
SELECT * FROM CATEGORY;
SELECT BAS_SEQ.CURRVAL FROM DUAL;
select * FROM COUPON;

INSERT INTO category VALUES(300,'과일');

INSERT INTO ITEMINFO VALUES(3,'사과',300,1900,'A지점','한국',232,'2021/3/1',SYSDATE,'apple.jpg',1);

INSERT INTO MEMBERINFO VALUES(23,'test','1234','1','27','test@naver.com','양천구 신월동',sysdate,'0101111','0','1');

INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,23,1,0);

INSERT INTO COUPON VALUES(100,'2040/03/03',23,'가입쿠폰:2000',1);
COMMIT;
CREATE SEQUENCE LOGIID_SEQ;
CREATE SEQUENCE BUYID_SEQ;
SELECT * FROM BUYLIST;
SELECT * FROM LOGISTIC;
delete from buylist;
delete from logistic;
commit;

INSERT INTO LOGISTIC VALUES(LOGIID_SEQ.NEXTVAL,23,BUYID_SEQ.CURRVAL,1,'양천구','물품준비중');



--(아래부터는 편하게 데이터 쓰기위해 막 적어놓은것들)
INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),11,3);

INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),231,0);

SELECT * FROM BASKET;
DELETE FROM BASKET WHERE COUNT=0;
DELETE FROM BASKET WHERE BASID=;

DELETE FROM BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND ITEMID=11 AND COUNT=0;

SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0 ORDER BY BASID DESC;

rollback;
commit;
SELECT * FROM ITEMINFO;
SELECT * FROM MEMBERINFO;
INSERT INTO MEMBERINFO(MEMID,ID,PWD,ADDR,REGDATE,PHONE) VALUES(23,'test','1234','서울시',sysdate,'0101111');
INSERT INTO ITEMINFO(ITEMID,ITEMNAME,STOCK,EXPIRE,STOREDATE,image) VALUES(18,'스테이크',10,'2020/12/13',sysdate,'onion.jpg');
UPDATE ITEMINFO SET IMAGE='onion.jpg' WHERE ITEMID=11;