--찜목록에 추가기능 (아이디=? 11부분=?)
INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),11,0)
--찜목록 삭제기능 (아이디=? 11부분=?)
DELETE FROM BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND ITEMID=11 AND COUNT=0
--찜목록 보기 기능(아이디=?)
SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0


--(아래부터는 편하게 데이터 쓰기위해 막 적어놓은것들)
INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),11,3);

INSERT INTO BASKET VALUES(BAS_SEQ.NEXTVAL,(
SELECT MEMID FROM MEMBERINFO WHERE ID='test'),231,0);

SELECT * FROM BASKET;
DELETE FROM BASKET WHERE COUNT=0;
DELETE FROM BASKET WHERE BASID=;

DELETE FROM BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND ITEMID=11 AND COUNT=0;

SELECT * FROM ITEMINFO NATURAL JOIN BASKET WHERE MEMID=
(SELECT MEMID FROM MEMBERINFO WHERE ID='test') AND COUNT=0 ORDER BY BASID DESC;

rollback;
commit;
SELECT * FROM ITEMINFO;
SELECT * FROM MEMBERINFO;
INSERT INTO MEMBERINFO(MEMID,ID,PWD,ADDR,REGDATE,PHONE) VALUES(23,'test','1234','서울시',sysdate,'0101111');
INSERT INTO ITEMINFO(ITEMID,ITEMNAME,STOCK,EXPIRE,STOREDATE,image) VALUES(15,'만두',222,'2020/12/13',sysdate,'apple.jpg');
UPDATE ITEMINFO SET IMAGE='onion.jpg' WHERE ITEMID=11;